"""`regent advisor consult` — mechanized advisor consultation (PLAN-003).

Ports the IMP-003-proven CodexConsultAdapter: read-only sandboxed `codex exec`
with the REQ-003 §5 evidence tuple generated BY THE COMMAND, not by executor
discipline. Sandbox flags are mandatory and not configurable. Every terminal
outcome (SUCCESS/TIMEOUT/FAILURE) leaves the evidence pair complete.
"""

from __future__ import annotations

import os
import shutil
import tempfile
from pathlib import Path

from .evidence import EvidenceSet, header
from .process import SubprocessRunner

DEFAULT_VERDICT_RE = (r"^(CONCORDA|DISCORDA.*|APROVADO( COM RESSALVAS)?|"
                      r"REPROVADO|QUITADAS|PENDENTES.*)$")


class AdvisorUnavailable(Exception):
    pass


def run_consult(root: Path, *, prompt_file: Path, artifact: Path, linkage: str,
                timeout: float = 600.0, expect_verdict: str | None = None,
                runner=None, codex_bin: str = "codex") -> dict:
    root = Path(root)
    prompt_bytes = Path(prompt_file).read_bytes()  # byte-faithful (no newline
    # translation — read_text would normalize CRLF)
    prompt_text = prompt_bytes.decode("utf-8", errors="replace")
    evidence = EvidenceSet(Path(artifact),
                           {"prompt": Path(str(artifact) + "-PROMPT.md")})
    evidence.precheck()

    if runner is None:
        if shutil.which(codex_bin) is None:
            raise AdvisorUnavailable(f"'{codex_bin}' not found on PATH")
        runner = SubprocessRunner()

    evidence.write_sibling("prompt", prompt_bytes)  # byte-identical copy first

    fd, msg_file = tempfile.mkstemp(prefix="regent-consult-", suffix=".txt")
    os.close(fd)
    try:
        argv = [codex_bin, "--ask-for-approval", "never",
                "--sandbox", "read-only",  # MANDATORY, not configurable
                "exec", "--cd", str(root), "-o", msg_file, prompt_text]
        result = runner.run(argv, cwd=str(root), timeout=timeout)
        try:
            last_message = Path(msg_file).read_text(encoding="utf-8",
                                                    errors="replace")
        except OSError:
            last_message = ""
    except BaseException:
        evidence.cleanup_orphans()  # non-terminal: never leave half a pair
        raise
    finally:
        try:
            os.unlink(msg_file)
        except OSError:
            pass

    if result.timed_out:
        outcome = "TIMEOUT"
    elif result.exit_code != 0:
        outcome = "FAILURE"
    else:
        outcome = "SUCCESS"

    body = last_message if last_message.strip() else result.output
    pattern = expect_verdict if expect_verdict is not None else DEFAULT_VERDICT_RE
    verdict = _extract_verdict(body, pattern)
    evidence.write_main(header(outcome, result.exit_code, linkage,
                               verdict=verdict), body)

    verdict_ok = verdict is not None if expect_verdict is not None else True
    return {"ok": outcome == "SUCCESS" and verdict_ok, "outcome": outcome,
            "verdict": verdict, "exit_code": result.exit_code,
            "artifact": str(evidence.main),
            "prompt_copy": str(evidence.siblings["prompt"])}


def _extract_verdict(body: str, pattern: str) -> str | None:
    import re
    for line in reversed(body.splitlines()):
        line = line.strip()
        if line:
            return line if re.fullmatch(pattern, line) else None
    return None
